### ISSUE TITLE
WOQL query page goes blank

### ISSUE THREAD

**Issue by KostadinovK** [terminusdb-hub/terminusdb-live-pattern-library#20]
When a user is writing a WOQL query and it is incomplete ```WOQL.triple(``` for example and he runs it or focus out from the window and return back the query is executed and the whole page goes blank.
![Capture](https://user-images.githubusercontent.com/15365540/130974368-c0ada237-8061-4b62-998e-1dd0aaceff21.PNG)

**Comment by Francesca-Bit** [comment]
fixed
