### ISSUE TITLE
Documentation doesn't save from model builder 

### ISSUE THREAD

**Issue by KittyJose** [terminusdb-hub/terminusdb-live-pattern-library#25]
when I add a description to a property like below

![image](https://user-images.githubusercontent.com/54106287/131508620-25ccb9e3-e764-4cb9-a111-328eab0d60a6.png)

Documentation is not sent to the database to store. See below payload being sent. :) 

```
{
   "@id":"easy",
   "@inherits":"Entity",
   "@key":{
      "@type":"Random"
   },
   "@type":"Class",
   "thing":"xsd:string"
}

```

**Comment by Francesca-Bit** [comment]
fixed in dev
