### ISSUE TITLE
on input of gibberish in query pane, dashboard crashes 

### ISSUE THREAD

**Issue by KittyJose** [terminusdb-hub/terminusdb-live-pattern-library#26]
if I input any garbage into query pane, dashboard crashes instead should report back wrong WOQL syntax.

![image](https://user-images.githubusercontent.com/54106287/131871778-b9f0db4c-390b-4e72-b11c-515d15f0cf6e.png)

Eval crashes 

![image](https://user-images.githubusercontent.com/54106287/131871848-26a7a951-b782-4c63-abab-a71ecd64ccbd.png)

**Comment by Francesca-Bit** [comment]
fixed in main branch
