### ISSUE TITLE
Issue when signing up with a team name consisting of "/" 

### ISSUE THREAD

**Issue by Neelterminusdb** [terminusdb-hub/terminusdb-live-pattern-library#27]
I have registered on the dashboard with team name as Cloud/UX, so while connecting to the database using a client i am getting 404 notfound.

the connection URL will be https://cloud-dev.dcm.ist/Cloud/UX/  when i sign up using team name, so it get confused while connecting to the database.

The sign up form should have a validation check for team name for special characters which cannot be used with the URL.

**Comment by Francesca-Bit** [comment]
fixed in main (we escape all the character in the url)
