### ISSUE TITLE
Can't access top of login page with small vertical height

### ISSUE THREAD

**Issue by spl** [terminusdb-hub/terminusdb-live-pattern-library#3]
See the scrollbar on the right. I can't go higher without changing the window size.
![cant-scroll](https://user-images.githubusercontent.com/54900/129188604-53d157a3-8ad6-41ff-80ca-839f5a1f2ea6.jpg)

**Comment by KittyJose** [comment]
I think we will replace this login page one's we get from designers? I am not really sure on this ... maybe @vivek9209 @Francesca-Bit can comment on this ?

**Comment by KittyJose** [comment]
Ok Thanks @vivek9209,  @spl Closing this issue then yea :)
