### ISSUE TITLE
Interface disappears when selecting branch elipses

### ISSUE THREAD

**Issue by GavinMendelGleason** [terminusdb-hub/terminusdb-live-pattern-library#33]
When I select the "..." in the data product branches screen, my entire screen goes blank.

**Comment by GavinMendelGleason** [comment]
![Screenshot from 2021-09-13 14-53-53](https://user-images.githubusercontent.com/1993386/133087079-1f7b8ab9-afe4-4e5a-b47b-99669d6fe1d2.png)

**Comment by Francesca-Bit** [comment]
fixed
