### ISSUE TITLE
Collection delete button funniness

### ISSUE THREAD

**Issue by spl** [terminusdb-hub/terminusdb-live-pattern-library#5]
When I click the trash icon or the delete button for my `main` collection, nothing happens. When I click the same for a new collection (named “0”), I get an error: “Error: Error in deleteing branch - 0. undefined”. Note the typo, too: _deleting_
<img width="644" alt="delete-failure" src="https://user-images.githubusercontent.com/54900/129196543-51323871-dbb3-4e89-be8e-fdb4dacc82ad.png">

**Comment by KittyJose** [comment]
@spl  I have pushed a fix to dev, can you check this out and let me know ?
